export const COMMON_NAMES: Record<string, string> = {
  "Albatrellus pes-caprae": "Barbone",
  "Camarophyllus russocoriaceus": "Bianchinella",
  Russula: "Bietta",
  "Amanita vaginata": "Bubbolino-Pettinina",
  "Pleurotus eryngii": "Cardarello",
  "Hydnum repandum": "Carpinello",
  "Gomphidius glutinosus": "Mucigione",
  "Tricholoma acerbum": "Orlo",
  "Agaricus bisporus": "Champignon",
  "Chroogomphus rutilus": "Chiodetto",
  "Clitocybe geotropa": "Cimbello-Orinale",
  "Armillaria mellea": "Famigliola-Chiodino",
  "Kuehneromyces mutabilis": "Famigliola gialla-Chiodino",
  "Amanita ovoidea": "Farinaccio",
  "Marasmius oreades": "Filaiola-Cappelline o Gambesecche",
  "Cantharellus lutescens": "Finferla",
  "Omphalotus olearius": "Fungo dell'ulivo",
  "Cantharellus cibarius": "Galletto",
  "Hygrophorus russula": "Gallinaccio",
  "Pleurotus ostreatus": "Gelone-Orecchione",
  "Clitocybe gibba": "Imbutino",
  Ramaria: "Manine",
  "Macrolepiota procera": "Mazza di Tamburo",
  "Tricholoma terreum": "Moretta",
  "Amanita cesarea": "Ovolo",
  "Clitopilus prunulus": "Pastellina-Falso prugnolo",
  "Agrocybe aegerita": "Pioppino-Piopparello",
  Leccinum: "Porcinello",
  "Boletus edulis": "Porcino",
  Agaricus: "Prataiolo",
  "Camarophyllus pratensis": "Rosciolo",
  "Lactarius deliciosus": "Sanguinello",
  "Calocybe gambosa": "Spignolo-Prugnolo",
  "Clitocybe nebularis": "Spignolone-Orinale",
  "Lepista nuda": "Spignolone d'inverno",
  Morchella: "Spugnola",
  "Craterellus cornucopioides": "Trombetta dei morti",
  "Russula delica": "Tufarone",
  "Agaricus arvensis": "Turino",
  "Russula virescens": "Verdone",
  "Lycoperdon perlatum": "Vescia-Loffa",
  "Suillus granulatus": "Pinarolo",
  "Russula chloroides": "Pevrina",
  "Lactarius piperatus": "Pevrina dal latt",
  "Coprinus comatus": "Fungo dell'inchiostro",
};
