import type { ImageQuestion } from "@/lib/image-types";

export const imageQuestions: ImageQuestion[] = [
  {
    id: "2a-amanita-phalloides-1",
    group: "2a",
    image: "https://i.ibb.co/QvdYrJfY/2a-Amanita-phalloides-1.webp",
    name: "Amanita phalloides",
  },
  {
    id: "2a-amanita-phalloides-2",
    group: "2a",
    image: "https://i.ibb.co/bjB2DKkp/2a-Amanita-phalloides-2.webp",
    name: "Amanita phalloides",
  },
  {
    id: "2a-amanita-phalloides-3",
    group: "2a",
    image: "https://i.ibb.co/SXrK935c/2a-Amanita-phalloides-3.webp",
    name: "Amanita phalloides",
  },
  {
    id: "2a-amanita-phalloides-4",
    group: "2a",
    image: "https://i.ibb.co/TBqp1R6B/2a-Amanita-phalloides-4.webp",
    name: "Amanita phalloides",
  },
  {
    id: "2a-amanita-phalloides-5",
    group: "2a",
    image: "https://i.ibb.co/qMp1DtdS/2a-Amanita-phalloides-5.webp",
    name: "Amanita phalloides",
  },
  {
    id: "2a-amanita-phalloides-var-alba-1",
    group: "2a",
    image: "https://i.ibb.co/twccG7KM/2a-Amanita-phalloides-var-alba-1.webp",
    name: "Amanita phalloides var alba",
  },
  {
    id: "2a-amanita-phalloides-var-alba-2",
    group: "2a",
    image: "https://i.ibb.co/kVNRFykw/2a-Amanita-phalloides-var-alba-2.webp",
    name: "Amanita phalloides var alba",
  },
  {
    id: "2a-amanita-phalloides-var-alba-3",
    group: "2a",
    image: "https://i.ibb.co/vvMxN5sL/2a-Amanita-phalloides-var-alba-3.webp",
    name: "Amanita phalloides var alba",
  },
  {
    id: "2a-amanita-phalloides-var-alba-4",
    group: "2a",
    image: "https://i.ibb.co/ZpSH9GcB/2a-Amanita-phalloides-var-alba-4.webp",
    name: "Amanita phalloides var alba",
  },
  {
    id: "2a-amanita-phalloides-var-alba-5",
    group: "2a",
    image: "https://i.ibb.co/fGFLGZWF/2a-Amanita-phalloides-var-alba-5.webp",
    name: "Amanita phalloides var alba",
  },
  {
    id: "2a-amanita-verna-1",
    group: "2a",
    image: "https://i.ibb.co/ksNhC7XT/2a-Amanita-verna-1.webp",
    name: "Amanita verna",
  },
  {
    id: "2a-amanita-verna-2",
    group: "2a",
    image: "https://i.ibb.co/7t1cHzm3/2a-Amanita-verna-2.webp",
    name: "Amanita verna",
  },
  {
    id: "2a-amanita-verna-3",
    group: "2a",
    image: "https://i.ibb.co/vMnmMkk/2a-Amanita-verna-3.webp",
    name: "Amanita verna",
  },
  {
    id: "2a-amanita-verna-4",
    group: "2a",
    image: "https://i.ibb.co/7d1BKLrc/2a-Amanita-verna-4.webp",
    name: "Amanita verna",
  },
  {
    id: "2a-amanita-verna-5",
    group: "2a",
    image: "https://i.ibb.co/N2W4Pp1m/2a-Amanita-verna-5.webp",
    name: "Amanita verna",
  },
  {
    id: "2a-amanita-virosa-1",
    group: "2a",
    image: "https://i.ibb.co/Q7Fgf5zN/2a-Amanita-virosa-1.webp",
    name: "Amanita virosa",
  },
  {
    id: "2a-amanita-virosa-2",
    group: "2a",
    image: "https://i.ibb.co/sJcJ6SHc/2a-Amanita-virosa-2.webp",
    name: "Amanita virosa",
  },
  {
    id: "2a-amanita-virosa-3",
    group: "2a",
    image: "https://i.ibb.co/h1Lb8zSF/2a-Amanita-virosa-3.webp",
    name: "Amanita virosa",
  },
  {
    id: "2a-amanita-virosa-4",
    group: "2a",
    image: "https://i.ibb.co/C3jwYVpX/2a-Amanita-virosa-4.webp",
    name: "Amanita virosa",
  },
  {
    id: "2a-cortinarius-orellanus-1",
    group: "2a",
    image: "https://i.ibb.co/r2djDJVV/2a-Cortinarius-orellanus-1.webp",
    name: "Cortinarius orellanus",
  },
  {
    id: "2a-cortinarius-orellanus-2",
    group: "2a",
    image: "https://i.ibb.co/SDZXzdfc/2a-Cortinarius-orellanus-2.webp",
    name: "Cortinarius orellanus",
  },
  {
    id: "2a-cortinarius-orellanus-3",
    group: "2a",
    image: "https://i.ibb.co/20xqDsxm/2a-Cortinarius-orellanus-3.webp",
    name: "Cortinarius orellanus",
  },
  {
    id: "2a-cortinarius-orellanus-4",
    group: "2a",
    image: "https://i.ibb.co/9H3qqRZh/2a-Cortinarius-orellanus-4.webp",
    name: "Cortinarius orellanus",
  },
  {
    id: "2a-cortinarius-orellanus-5",
    group: "2a",
    image: "https://i.ibb.co/d0Yd6J21/2a-Cortinarius-orellanus-5.webp",
    name: "Cortinarius orellanus",
  },
  {
    id: "2a-cortinarius-speciosissimus-1",
    group: "2a",
    image: "https://i.ibb.co/6JNVp8GM/2a-Cortinarius-speciosissimus-1.webp",
    name: "Cortinarius speciosissimus",
  },
  {
    id: "2a-cortinarius-speciosissimus-2",
    group: "2a",
    image: "https://i.ibb.co/tTzyR3v8/2a-Cortinarius-speciosissimus-2.webp",
    name: "Cortinarius speciosissimus",
  },
  {
    id: "2a-cortinarius-speciosissimus-3",
    group: "2a",
    image: "https://i.ibb.co/jnzQ6Mq/2a-Cortinarius-speciosissimus-3.webp",
    name: "Cortinarius speciosissimus",
  },
  {
    id: "2a-galerina-marginata-1",
    group: "2a",
    image: "https://i.ibb.co/S4JjHGtL/2a-Galerina-marginata-1.webp",
    name: "Galerina marginata",
  },
  {
    id: "2a-gyromitra-esculenta-1",
    group: "2a",
    image: "https://i.ibb.co/9mJHNJSz/2a-Gyromitra-esculenta-1.webp",
    name: "Gyromitra esculenta",
  },
  {
    id: "2a-lepiota-brunneoincarnata-1",
    group: "2a",
    image: "https://i.ibb.co/hrDsBdz/2a-Lepiota-brunneoincarnata-1.webp",
    name: "Lepiota brunneoincarnata",
  },
  {
    id: "2a-lepiota-brunneoincarnata-2",
    group: "2a",
    image: "https://i.ibb.co/spnhm4zy/2a-Lepiota-brunneoincarnata-2.webp",
    name: "Lepiota brunneoincarnata",
  },
  {
    id: "2a-lepiota-helveola-1",
    group: "2a",
    image: "https://i.ibb.co/QvKm9Pj7/2a-Lepiota-helveola-1.webp",
    name: "Lepiota helveola",
  },
  {
    id: "2a-lepiota-helveola-2",
    group: "2a",
    image: "https://i.ibb.co/qhxP4Lr/2a-Lepiota-helveola-2.webp",
    name: "Lepiota helveola",
  },
  {
    id: "2a-lepiota-subincarnata-1",
    group: "2a",
    image: "https://i.ibb.co/GBLhjd8/2a-Lepiota-subincarnata-1.webp",
    name: "Lepiota subincarnata",
  },
  {
    id: "2a-lepiota-subincarnata-2",
    group: "2a",
    image: "https://i.ibb.co/cX6r7djp/2a-Lepiota-subincarnata-2.webp",
    name: "Lepiota subincarnata",
  },
  {
    id: "2a-lepiota-subincarnata-3",
    group: "2a",
    image: "https://i.ibb.co/8LhqjZHv/2a-Lepiota-subincarnata-3.webp",
    name: "Lepiota subincarnata",
  },
  {
    id: "2a-trcholoma-equestre-1",
    group: "2a",
    image: "https://i.ibb.co/rfHczgNd/2a-Trcholoma-equestre-1.webp",
    name: "Tricholoma equestre",
  },
  {
    id: "2a-tricholoma-equestre-2",
    group: "2a",
    image: "https://i.ibb.co/C55fNZzn/2a-Tricholoma-equestre-2.webp",
    name: "Tricholoma equestre",
  },
  {
    id: "2a-tricholoma-equestre-3",
    group: "2a",
    image: "https://i.ibb.co/yB7QsqmX/2a-Tricholoma-equestre-3.webp",
    name: "Tricholoma equestre",
  },
  {
    id: "2a-tricholoma-equestre-4",
    group: "2a",
    image: "https://i.ibb.co/HTcWq5XK/2a-Tricholoma-equestre-4.webp",
    name: "Tricholoma equestre",
  },
  {
    id: "2a-tricholoma-equestre-5",
    group: "2a",
    image: "https://i.ibb.co/Y7BJ1ZGk/2a-Tricholoma-equestre-5.webp",
    name: "Tricholoma equestre",
  },
  {
    id: "2a-tricholoma-equestre-6",
    group: "2a",
    image: "https://i.ibb.co/pBsBWY9J/2a-Tricholoma-equestre-6.webp",
    name: "Tricholoma equestre",
  },
  {
    id: "2a-tricholoma-equestre-7",
    group: "2a",
    image: "https://i.ibb.co/xtLZq53h/2a-Tricholoma-equestre-7.webp",
    name: "Tricholoma equestre",
  },

  {
    id: "2b-agaricus-bresadolanus-2",
    group: "2b",
    image: "https://i.ibb.co/0yxbyVvS/2b-Agaricus-bresadolanus-2.webp",
    name: "Agaricus bresadolanus",
  },
  {
    id: "2b-agaricus-bresadolanus",
    group: "2b",
    image: "https://i.ibb.co/PvYXYCG6/2b-Agaricus-bresadolanus.webp",
    name: "Agaricus bresadolanus",
  },
  {
    id: "2b-agaricus-xanthodermus-1",
    group: "2b",
    image: "https://i.ibb.co/nsT9cd1c/2b-Agaricus-xanthodermus-1.webp",
    name: "Agaricus xanthodermus",
  },
  {
    id: "2b-agaricus-xanthodermus-2",
    group: "2b",
    image: "https://i.ibb.co/F41pK6YB/2b-Agaricus-xanthodermus-2.webp",
    name: "Agaricus xanthodermus",
  },
  {
    id: "2b-amanita-muscaria-1",
    group: "2b",
    image: "https://i.ibb.co/7JCtBzx8/2b-Amanita-muscaria-1.webp",
    name: "Amanita muscaria",
  },
  {
    id: "2b-amanita-muscaria-2",
    group: "2b",
    image: "https://i.ibb.co/cS2KXF8S/2b-Amanita-muscaria-2.webp",
    name: "Amanita muscaria",
  },
  {
    id: "2b-amanita-pantherina-1",
    group: "2b",
    image: "https://i.ibb.co/35v8d7dx/2b-Amanita-pantherina-1.webp",
    name: "Amanita pantherina",
  },
  {
    id: "2b-amanita-pantherina-2",
    group: "2b",
    image: "https://i.ibb.co/vvRTRFT3/2b-Amanita-pantherina-2.webp",
    name: "Amanita pantherina",
  },
  {
    id: "2b-clitocybe-dealbata-1",
    group: "2b",
    image: "https://i.ibb.co/C5nrp2JM/2b-Clitocybe-dealbata-1.webp",
    name: "Clitocybe dealbata",
  },
  {
    id: "2b-clitocybe-dealbata-2",
    group: "2b",
    image: "https://i.ibb.co/hRwzKf04/2b-Clitocybe-dealbata-2.webp",
    name: "Clitocybe dealbata",
  },
  {
    id: "2b-entoloma-sinuatum-1",
    group: "2b",
    image: "https://i.ibb.co/HDXnmpMG/2b-Entoloma-sinuatum-1.webp",
    name: "Entoloma sinuatum",
  },
  {
    id: "2b-entoloma-sinuatum-2",
    group: "2b",
    image: "https://i.ibb.co/JWKB7fVN/2b-Entoloma-sinuatum-2.webp",
    name: "Entoloma sinuatum",
  },
  {
    id: "2b-entoloma-sinuatum-3",
    group: "2b",
    image: "https://i.ibb.co/jkkmTVTw/2b-Entoloma-sinuatum-3.webp",
    name: "Entoloma sinuatum",
  },
  {
    id: "2b-entoloma-sinuatum-4",
    group: "2b",
    image: "https://i.ibb.co/jk5Jskv9/2b-Entoloma-sinuatum-4.webp",
    name: "Entoloma sinuatum",
  },
  {
    id: "2b-entolona-sinuatum-5",
    group: "2b",
    image: "https://i.ibb.co/VWMVLbh3/2b-Entolona-sinuatum-5.webp",
    name: "Entoloma sinuatum",
  },
  {
    id: "2b-hebeloma-sinapizans-1",
    group: "2b",
    image: "https://i.ibb.co/JjVJB7Jx/2b-Hebeloma-sinapizans-1.webp",
    name: "Hebeloma sinapizans",
  },
  {
    id: "2b-hebeloma-sinapizans-2",
    group: "2b",
    image: "https://i.ibb.co/kYtdgsY/2b-Hebeloma-sinapizans-2.webp",
    name: "Hebeloma sinapizans",
  },
  {
    id: "2b-hypholoma-fasciculare-1",
    group: "2b",
    image: "https://i.ibb.co/xtRymHHn/2b-Hypholoma-fasciculare-1.webp",
    name: "Hypholoma fasciculare",
  },
  {
    id: "2b-hypholoma-fasciculare-2",
    group: "2b",
    image: "https://i.ibb.co/N20XtbDg/2b-Hypholoma-fasciculare-2.webp",
    name: "Hypholoma fasciculare",
  },
  {
    id: "2b-hypholoma-fasciculare-3",
    group: "2b",
    image: "https://i.ibb.co/HTZqmKNR/2b-Hypholoma-fasciculare-3.webp",
    name: "Hypholoma fasciculare",
  },
  {
    id: "2b-hypholoma-lateritium-1",
    group: "2b",
    image: "https://i.ibb.co/fGXhhb92/2b-Hypholoma-lateritium-1.webp",
    name: "Hypholoma lateritium",
  },
  {
    id: "2b-hypholoma-lateritium-2",
    group: "2b",
    image: "https://i.ibb.co/XZfxPFLC/2b-Hypholoma-lateritium-2.webp",
    name: "Hypholoma lateritium",
  },
  {
    id: "2b-inocybe-fastigiata-1",
    group: "2b",
    image: "https://i.ibb.co/SXHcWYgR/2b-Inocybe-fastigiata-1.webp",
    name: "Inocybe fastigiata",
  },
  {
    id: "2b-inocybe-fastigiata-2",
    group: "2b",
    image: "https://i.ibb.co/7NTz3ts4/2b-Inocybe-fastigiata-2.webp",
    name: "Inocybe fastigiata",
  },
  {
    id: "2b-inocybe-fastigiata-3",
    group: "2b",
    image: "https://i.ibb.co/m5FV7XjF/2b-Inocybe-fastigiata-3.webp",
    name: "Inocybe fastigiata",
  },
  {
    id: "2b-inocybe-fastigiata-4",
    group: "2b",
    image: "https://i.ibb.co/21T7RW5s/2b-Inocybe-fastigiata-4.webp",
    name: "Inocybe fastigiata",
  },
  {
    id: "2b-inocybe-fastigiata-5",
    group: "2b",
    image: "https://i.ibb.co/JWZ19y1c/2b-Inocybe-fastigiata-5.webp",
    name: "Inocybe fastigiata",
  },
  {
    id: "2b-inocybe-fastigiata-6",
    group: "2b",
    image: "https://i.ibb.co/jvT10w9H/2b-Inocybe-fastigiata-6.webp",
    name: "Inocybe fastigiata",
  },
  {
    id: "2b-inocybe-fastigiata-8",
    group: "2b",
    image: "https://i.ibb.co/wNDBQ8Xd/2b-Inocybe-fastigiata-8.webp",
    name: "Inocybe fastigiata",
  },
  {
    id: "2b-inocybe-fastigiata-9",
    group: "2b",
    image: "https://i.ibb.co/Tqr43z8Z/2b-Inocybe-fastigiata-9.webp",
    name: "Inocybe fastigiata",
  },
  {
    id: "2b-inocybe-fastigiata-10",
    group: "2b",
    image: "https://i.ibb.co/Rp0ntsrd/2b-Inocybe-fastigiata-10.webp",
    name: "Inocybe fastigiata",
  },
  {
    id: "2b-lactarius-piperatus-1",
    group: "2b",
    image: "https://i.ibb.co/ynN4cLKN/2b-Lactarius-piperatus-1.webp",
    name: "Lactarius piperatus",
  },
  {
    id: "2b-lactarius-piperatus-2",
    group: "2b",
    image: "https://i.ibb.co/nMbjGv3b/2b-Lactarius-piperatus-2.webp",
    name: "Lactarius piperatus",
  },
  {
    id: "2b-lepiota-cristata-1",
    group: "2b",
    image: "https://i.ibb.co/4nP0D3vz/2b-Lepiota-cristata-1.webp",
    name: "Lepiota cristata",
  },
  {
    id: "2b-lepiota-cristata-2",
    group: "2b",
    image: "https://i.ibb.co/SXbX61pC/2b-Lepiota-cristata-2.webp",
    name: "Lepiota cristata",
  },
  {
    id: "2b-mycena-pura-1",
    group: "2b",
    image: "https://i.ibb.co/3YQ2R2VM/2b-Mycena-pura-1.webp",
    name: "Mycena pura",
  },
  {
    id: "2b-mycena-pura-2",
    group: "2b",
    image: "https://i.ibb.co/99XRGv95/2b-Mycena-pura-2.webp",
    name: "Mycena pura",
  },
  {
    id: "2b-mycena-pura-3",
    group: "2b",
    image: "https://i.ibb.co/F4dy1jB2/2b-Mycena-pura-3.webp",
    name: "Mycena pura",
  },
  {
    id: "2b-omphalotus-olearius-1",
    group: "2b",
    image: "https://i.ibb.co/XrjWvWHQ/2b-Omphalotus-olearius-1.webp",
    name: "Omphalotus olearius",
  },
  {
    id: "2b-omphalotus-olearius-2",
    group: "2b",
    image: "https://i.ibb.co/Jj7VQ5Cr/2b-Omphalotus-olearius-2.webp",
    name: "Omphalotus olearius",
  },
  {
    id: "2b-omphalotus-olearius-3",
    group: "2b",
    image: "https://i.ibb.co/bRFNJY8p/2b-Omphalotus-olearius-3.webp",
    name: "Omphalotus olearius",
  },
  {
    id: "2b-omphalotus-olearius-4",
    group: "2b",
    image: "https://i.ibb.co/9kbXWtPV/2b-Omphalotus-olearius-4.webp",
    name: "Omphalotus olearius",
  },
  {
    id: "2b-omphalotus-olearius-5",
    group: "2b",
    image: "https://i.ibb.co/k2qpyQzf/2b-Omphalotus-olearius-5.webp",
    name: "Omphalotus olearius",
  },
  {
    id: "2b-paxillus-involutus-1",
    group: "2b",
    image: "https://i.ibb.co/Q38BMycz/2b-Paxillus-involutus-1.webp",
    name: "Paxillus involutus",
  },
  {
    id: "2b-paxillus-involutus-2",
    group: "2b",
    image: "https://i.ibb.co/ynJYc1SH/2b-Paxillus-involutus-2.webp",
    name: "Paxillus involutus",
  },
  {
    id: "2b-paxillus-involutus-3",
    group: "2b",
    image: "https://i.ibb.co/GfmtsCXP/2b-Paxillus-involutus-3.webp",
    name: "Paxillus involutus",
  },
  {
    id: "2b-ramaria-formosa-10610",
    group: "2b",
    image: "https://i.ibb.co/jkTqJZx6/2b-Ramaria-formosa-10610.webp",
    name: "Ramaria formosa",
  },
  {
    id: "2b-ramaria-formosa",
    group: "2b",
    image: "https://i.ibb.co/pvRF4qsH/2b-Ramaria-formosa.webp",
    name: "Ramaria formosa",
  },
  {
    id: "2b-rubroboletus-lupinus-1",
    group: "2b",
    image: "https://i.ibb.co/Nz00Gt4/2b-Rubroboletus-lupinus-1.webp",
    name: "Rubroboletus lupinus",
  },
  {
    id: "2b-rubroboletus-lupinus-2",
    group: "2b",
    image: "https://i.ibb.co/Kp9phwNY/2b-Rubroboletus-lupinus-2.webp",
    name: "Rubroboletus lupinus",
  },
  {
    id: "2b-rubroboletus-lupinus-3",
    group: "2b",
    image: "https://i.ibb.co/fV1Pg0N6/2b-Rubroboletus-lupinus-3.webp",
    name: "Rubroboletus lupinus",
  },
  {
    id: "2b-rubroboletus-satanas-1",
    group: "2b",
    image: "https://i.ibb.co/n4N4qmQ/2b-Rubroboletus-satanas-1.webp",
    name: "Rubroboletus satanas",
  },
  {
    id: "2b-rubroboletus-satanas-2",
    group: "2b",
    image: "https://i.ibb.co/fz7GQV9d/2b-Rubroboletus-satanas-2.webp",
    name: "Rubroboletus satanas",
  },
  {
    id: "2b-rubroboletus-satanas-3",
    group: "2b",
    image: "https://i.ibb.co/7dZRVC6S/2b-Rubroboletus-satanas-3.webp",
    name: "Rubroboletus satanas",
  },
  {
    id: "2b-rubroboletus-satanas-4",
    group: "2b",
    image: "https://i.ibb.co/ZpLfk48N/2b-Rubroboletus-satanas-4.webp",
    name: "Rubroboletus satanas",
  },
  {
    id: "2b-russula-luteotacta-2",
    group: "2b",
    image: "https://i.ibb.co/Hp28pSJN/2b-Russula-luteotacta-2.webp",
    name: "Russula luteotacta",
  },
  {
    id: "2b-russula-luteotacta-2714",
    group: "2b",
    image: "https://i.ibb.co/FbFSmSBz/2b-Russula-luteotacta-2714.webp",
    name: "Russula luteotacta",
  },
  {
    id: "2b-russula-torulosa-1",
    group: "2b",
    image: "https://i.ibb.co/JjrtR8ML/2b-Russula-torulosa-1.webp",
    name: "Russula torulosa",
  },
  {
    id: "2b-russula-torulosa-2",
    group: "2b",
    image: "https://i.ibb.co/fzYwgcKY/2b-Russula-torulosa-2.webp",
    name: "Russula torulosa",
  },
  {
    id: "2b-tricholoma-bresadolanum-1",
    group: "2b",
    image: "https://i.ibb.co/2Yty512n/2b-Tricholoma-bresadolanum-1.webp",
    name: "Tricholoma bresadolanum",
  },
  {
    id: "2b-tricholoma-bresadolanum-2",
    group: "2b",
    image: "https://i.ibb.co/1Ykbhdqg/2b-Tricholoma-bresadolanum-2.webp",
    name: "Tricholoma bresadolanum",
  },
  {
    id: "2b-tricholoma-bresadolanum-3",
    group: "2b",
    image: "https://i.ibb.co/HpFTVXhn/2b-Tricholoma-bresadolanum-3.webp",
    name: "Tricholoma bresadolanum",
  },
  {
    id: "2b-tricholoma-pardinum-1",
    group: "2b",
    image: "https://i.ibb.co/v9pk882/2b-Tricholoma-pardinum-1.webp",
    name: "Tricholoma pardinum",
  },
  {
    id: "2b-tricholoma-pardinum-2",
    group: "2b",
    image: "https://i.ibb.co/fVsCvqQ1/2b-Tricholoma-pardinum-2.webp",
    name: "Tricholoma pardinum",
  },
  {
    id: "2b-tricholoma-pardinum-3",
    group: "2b",
    image: "https://i.ibb.co/CKfJFtx9/2b-Tricholoma-pardinum-3.webp",
    name: "Tricholoma pardinum",
  },
  {
    id: "2b-tricholoma-pardinum-4",
    group: "2b",
    image: "https://i.ibb.co/p6NH5qFb/2b-Tricholoma-pardinum-4.webp",
    name: "Tricholoma pardinum",
  },
  {
    id: "2b-tricholoma-pardinum-5",
    group: "2b",
    image: "https://i.ibb.co/ZRrqbW4W/2b-Tricholoma-pardinum-5.webp",
    name: "Tricholoma pardinum",
  },
  {
    id: "2b-tricholoma-sulphureum-1",
    group: "2b",
    image: "https://i.ibb.co/tT0cSHRd/2b-Tricholoma-sulphureum-1.webp",
    name: "Tricholoma sulphureum",
  },
  {
    id: "2b-tricholoma-sulphureum-2",
    group: "2b",
    image: "https://i.ibb.co/bZPQKWb/2b-Tricholoma-sulphureum-2.webp",
    name: "Tricholoma sulphureum",
  },

  {
    id: "2c-agaricus-arvensis-1",
    group: "2c",
    image: "https://i.ibb.co/q3CnPLDZ/2c-Agaricus-arvensis-1.webp",
    name: "Agaricus arvensis",
  },
  {
    id: "2c-agaricus-arvensis-2",
    group: "2c",
    image: "https://i.ibb.co/vxRF3WR1/2c-Agaricus-arvensis-2.webp",
    name: "Agaricus arvensis",
  },
  {
    id: "2c-agaricus-bitorquis-1",
    group: "2c",
    image: "https://i.ibb.co/V1JMQyL/2c-Agaricus-bitorquis-1.webp",
    name: "Agaricus bitorquis",
  },
  {
    id: "2c-agaricus-bitorquis-2",
    group: "2c",
    image: "https://i.ibb.co/HD525jsM/2c-Agaricus-bitorquis-2.webp",
    name: "Agaricus bitorquis",
  },
  {
    id: "2c-agaricus-bitorquis-3",
    group: "2c",
    image: "https://i.ibb.co/s9wkhHrg/2c-Agaricus-bitorquis-3.webp",
    name: "Agaricus bitorquis",
  },
  {
    id: "2c-agaricus-bitorquis-4",
    group: "2c",
    image: "https://i.ibb.co/Swj4Cy7q/2c-Agaricus-bitorquis-4.webp",
    name: "Agaricus bitorquis",
  },
  {
    id: "2c-agaricus-campestris-1",
    group: "2c",
    image: "https://i.ibb.co/WN2jbcLB/2c-Agaricus-campestris-1.webp",
    name: "Agaricus campestris",
  },
  {
    id: "2c-agaricus-campestris-2",
    group: "2c",
    image: "https://i.ibb.co/T39dm4V/2c-Agaricus-campestris-2.webp",
    name: "Agaricus campestris",
  },
  {
    id: "2c-agaricus-crocodilinus-1",
    group: "2c",
    image: "https://i.ibb.co/M5MkDs7B/2c-Agaricus-crocodilinus-1.webp",
    name: "Agaricus crocodilinus",
  },
  {
    id: "2c-agaricus-crocodilinus-2",
    group: "2c",
    image: "https://i.ibb.co/5xs5QZng/2c-Agaricus-crocodilinus-2.webp",
    name: "Agaricus crocodilinus",
  },
  {
    id: "2c-agaricus-crocodilinus-8",
    group: "2c",
    image: "https://i.ibb.co/4HCj4wb/2c-Agaricus-crocodilinus-8.webp",
    name: "Agaricus crocodilinus",
  },
  {
    id: "2c-agaricus-crocodillinus-3",
    group: "2c",
    image: "https://i.ibb.co/Psn7vZgg/2c-Agaricus-crocodillinus-3.webp",
    name: "Agaricus crocodilinus",
  },
  {
    id: "2c-agaricus-crocodillinus-4",
    group: "2c",
    image: "https://i.ibb.co/C5QPHvJF/2c-Agaricus-crocodillinus-4.webp",
    name: "Agaricus crocodilinus",
  },
  {
    id: "2c-agaricus-crocodillinus-5",
    group: "2c",
    image: "https://i.ibb.co/0ybz7NTh/2c-Agaricus-crocodillinus-5.webp",
    name: "Agaricus crocodilinus",
  },
  {
    id: "2c-agaricus-crocodillinus-6",
    group: "2c",
    image: "https://i.ibb.co/YTf0Y3hp/2c-Agaricus-crocodillinus-6.webp",
    name: "Agaricus crocodilinus",
  },
  {
    id: "2c-agaricus-crocodillinus-7",
    group: "2c",
    image: "https://i.ibb.co/WvXTWPZy/2c-Agaricus-crocodillinus-7.webp",
    name: "Agaricus crocodilinus",
  },
  {
    id: "2c-amanita-caesarea-1",
    group: "2c",
    image: "https://i.ibb.co/mCcyHyYD/2c-Amanita-caesarea-1.webp",
    name: "Amanita caesarea",
  },
  {
    id: "2c-amanita-caesarea-2",
    group: "2c",
    image: "https://i.ibb.co/20nHBvLz/2c-Amanita-caesarea-2.webp",
    name: "Amanita caesarea",
  },
  {
    id: "2c-amanita-caesarea-ovulo-3",
    group: "2c",
    image: "https://i.ibb.co/Lh2Wsxqg/2c-Amanita-caesarea-ovulo-3.webp",
    name: "Amanita caesarea",
  },
  {
    id: "2c-armillaria-mellea-1",
    group: "2c",
    image: "https://i.ibb.co/C4YVkqk/2c-Armillaria-mellea-1.webp",
    name: "Armillaria mellea",
  },
  {
    id: "2c-armillaria-mellea-2",
    group: "2c",
    image: "https://i.ibb.co/B53mtcyK/2c-Armillaria-mellea-2.webp",
    name: "Armillaria mellea",
  },
  {
    id: "2c-armillaria-mellea-3",
    group: "2c",
    image: "https://i.ibb.co/CsvxWb9W/2c-Armillaria-mellea-3.webp",
    name: "Armillaria mellea",
  },
  {
    id: "2c-armillaria-mellea-4",
    group: "2c",
    image: "https://i.ibb.co/WvqL3VjZ/2c-Armillaria-mellea-4.webp",
    name: "Armillaria mellea",
  },
  {
    id: "2c-auricularia-auricola-judae-1",
    group: "2c",
    image: "https://i.ibb.co/Z64ZfBw4/2c-Auricularia-auricola-judae-1.webp",
    name: "Auricularia auricula-judae",
  },
  {
    id: "2c-auricularia-auricola-judae-2",
    group: "2c",
    image: "https://i.ibb.co/BVnQXxRm/2c-Auricularia-auricola-judae-2.webp",
    name: "Auricularia auricula-judae",
  },
  {
    id: "2c-auricularia-auricola-judae-3",
    group: "2c",
    image: "https://i.ibb.co/LXrfGzdJ/2c-Auricularia-auricola-judae-3.webp",
    name: "Auricularia auricula-judae",
  },
  {
    id: "2c-boletus-aereus-1",
    group: "2c",
    image: "https://i.ibb.co/JjmdGfB6/2c-Boletus-aereus-1.webp",
    name: "Boletus aereus",
  },
  {
    id: "2c-boletus-aereus-2",
    group: "2c",
    image: "https://i.ibb.co/gFBLGbLs/2c-Boletus-aereus-2.webp",
    name: "Boletus aereus",
  },
  {
    id: "2c-boletus-aestivalis-1",
    group: "2c",
    image: "https://i.ibb.co/gLXVt78w/2c-Boletus-aestivalis-1.webp",
    name: "Boletus aestivalis",
  },
  {
    id: "2c-boletus-aestivalis-2",
    group: "2c",
    image: "https://i.ibb.co/5xs43NVH/2c-Boletus-aestivalis-2.webp",
    name: "Boletus aestivalis",
  },
  {
    id: "2c-boletus-aestivalis-3",
    group: "2c",
    image: "https://i.ibb.co/ymxj9Gjq/2c-Boletus-aestivalis-3.webp",
    name: "Boletus aestivalis",
  },
  {
    id: "2c-boletus-aestivalis-4",
    group: "2c",
    image: "https://i.ibb.co/GwgnS4M/2c-Boletus-aestivalis-4.webp",
    name: "Boletus aestivalis",
  },
  {
    id: "2c-boletus-edulis-1",
    group: "2c",
    image: "https://i.ibb.co/dwsyJQKr/2c-Boletus-edulis-1.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-2",
    group: "2c",
    image: "https://i.ibb.co/VYnBWCYP/2c-Boletus-edulis-2.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-3",
    group: "2c",
    image: "https://i.ibb.co/qLrGWfyj/2c-Boletus-edulis-3.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-4",
    group: "2c",
    image: "https://i.ibb.co/g1fPqVs/2c-Boletus-edulis-4.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-5",
    group: "2c",
    image: "https://i.ibb.co/YFLTjN6d/2c-Boletus-edulis-5.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-6",
    group: "2c",
    image: "https://i.ibb.co/TD21LgYR/2c-Boletus-edulis-6.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-7",
    group: "2c",
    image: "https://i.ibb.co/8nWFvQ94/2c-Boletus-edulis-7.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-8",
    group: "2c",
    image: "https://i.ibb.co/7xp4KbZt/2c-Boletus-edulis-8.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-9",
    group: "2c",
    image: "https://i.ibb.co/MxGC3Lgt/2c-Boletus-edulis-9.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-10",
    group: "2c",
    image: "https://i.ibb.co/jPpNs98m/2c-Boletus-edulis-10.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-11",
    group: "2c",
    image: "https://i.ibb.co/1G34cZCH/2c-Boletus-edulis-11.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-12",
    group: "2c",
    image: "https://i.ibb.co/jv2zY2FB/2c-Boletus-edulis-12.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-edulis-13",
    group: "2c",
    image: "https://i.ibb.co/pr118vvc/2c-Boletus-edulis-13.webp",
    name: "Boletus edulis",
  },
  {
    id: "2c-boletus-pinophilus-1",
    group: "2c",
    image: "https://i.ibb.co/kVMrHyKY/2c-Boletus-pinophilus-1.webp",
    name: "Boletus pinophilus",
  },
  {
    id: "2c-boletus-pinophilus-2",
    group: "2c",
    image: "https://i.ibb.co/spL7MdZj/2c-Boletus-pinophilus-2.webp",
    name: "Boletus pinophilus",
  },
  {
    id: "2c-boletus-pinophilus-3",
    group: "2c",
    image: "https://i.ibb.co/DP1z9g8D/2c-Boletus-pinophilus-3.webp",
    name: "Boletus pinophilus",
  },
  {
    id: "2c-boletus-pinophilus-4",
    group: "2c",
    image: "https://i.ibb.co/N2Z1Sg45/2c-Boletus-pinophilus-4.webp",
    name: "Boletus pinophilus",
  },
  {
    id: "2c-boletus-pinophilus-5",
    group: "2c",
    image: "https://i.ibb.co/KjfXgWrb/2c-Boletus-pinophilus-5.webp",
    name: "Boletus pinophilus",
  },
  {
    id: "2c-boletus-pinophilus-6",
    group: "2c",
    image: "https://i.ibb.co/jP5v8Bjw/2c-Boletus-pinophilus-6.webp",
    name: "Boletus pinophilus",
  },
  {
    id: "2c-buthyriboletus-regius-1",
    group: "2c",
    image: "https://i.ibb.co/ns245rX2/2c-Buthyriboletus-regius-1.webp",
    name: "Buthyriboletus regius",
  },
  {
    id: "2c-buthyriboletus-regius-2",
    group: "2c",
    image: "https://i.ibb.co/Rpzj6CNF/2c-Buthyriboletus-regius-2.webp",
    name: "Buthyriboletus regius",
  },
  {
    id: "2c-buthyriboletus-regius-3",
    group: "2c",
    image: "https://i.ibb.co/SDy1Jkxh/2c-Buthyriboletus-regius-3.webp",
    name: "Buthyriboletus regius",
  },
  {
    id: "2c-calocybe-gambosa-1",
    group: "2c",
    image: "https://i.ibb.co/zTQGThYT/2c-Calocybe-gambosa-1.webp",
    name: "Calocybe gambosa",
  },
  {
    id: "2c-calocybe-gambosa-2",
    group: "2c",
    image: "https://i.ibb.co/pmHxyp7/2c-Calocybe-gambosa-2.webp",
    name: "Calocybe gambosa",
  },
  {
    id: "2c-calocybe-gambosa-3",
    group: "2c",
    image: "https://i.ibb.co/HpkzvLJr/2c-Calocybe-gambosa-3.webp",
    name: "Calocybe gambosa",
  },
  {
    id: "2c-calocybe-gambosa-4",
    group: "2c",
    image: "https://i.ibb.co/v483z3Gp/2c-Calocybe-gambosa-4.webp",
    name: "Calocybe gambosa",
  },
  {
    id: "2c-calocybe-gambosa-5",
    group: "2c",
    image: "https://i.ibb.co/Jwcg1pbM/2c-Calocybe-gambosa-5.webp",
    name: "Calocybe gambosa",
  },
  {
    id: "2c-cantharellus-cibarius-1",
    group: "2c",
    image: "https://i.ibb.co/m5MZNj4t/2c-Cantharellus-cibarius-1.webp",
    name: "Cantharellus cibarius",
  },
  {
    id: "2c-cantharellus-cibarius-2",
    group: "2c",
    image: "https://i.ibb.co/mpNVWzm/2c-Cantharellus-cibarius-2.webp",
    name: "Cantharellus cibarius",
  },
  {
    id: "2c-cantharellus-lutescens-1",
    group: "2c",
    image: "https://i.ibb.co/vCkgQ7bY/2c-Cantharellus-lutescens-1.webp",
    name: "Cantharellus lutescens",
  },
  {
    id: "2c-cantharellus-lutescens-2",
    group: "2c",
    image: "https://i.ibb.co/ZpqyPJrX/2c-Cantharellus-lutescens-2.webp",
    name: "Cantharellus lutescens",
  },
  {
    id: "2c-cantharellus-lutescens-3",
    group: "2c",
    image: "https://i.ibb.co/Xkx5X7gN/2c-Cantharellus-lutescens-3.webp",
    name: "Cantharellus lutescens",
  },
  {
    id: "2c-craterellus-cornucopioides-1",
    group: "2c",
    image: "https://i.ibb.co/p9NxPJ2/2c-Craterellus-cornucopioides-1.webp",
    name: "Craterellus cornucopioides",
  },
  {
    id: "2c-craterellus-cornucopioides-2",
    group: "2c",
    image: "https://i.ibb.co/HpfQT4p5/2c-Craterellus-cornucopioides-2.webp",
    name: "Craterellus cornucopioides",
  },
  {
    id: "2c-cuphophyllus-pratensis-1",
    group: "2c",
    image: "https://i.ibb.co/gZqcYKxR/2c-Cuphophyllus-pratensis-1.webp",
    name: "Cuphophyllus pratensis",
  },
  {
    id: "2c-cuphophyllus-pratensis-2",
    group: "2c",
    image: "https://i.ibb.co/F4YX402K/2c-Cuphophyllus-pratensis-2.webp",
    name: "Cuphophyllus pratensis",
  },
  {
    id: "2c-cyclocybe-aegerita-1",
    group: "2c",
    image: "https://i.ibb.co/9mk6t2qw/2c-Cyclocybe-aegerita-1.webp",
    name: "Cyclocybe aegerita",
  },
  {
    id: "2c-cyclocybe-aegerita-2",
    group: "2c",
    image: "https://i.ibb.co/Xk6bszKj/2c-Cyclocybe-aegerita-2.webp",
    name: "Cyclocybe aegerita",
  },
  {
    id: "2c-cyclocybe-aegerita-3",
    group: "2c",
    image: "https://i.ibb.co/dw5Pgnk4/2c-Cyclocybe-aegerita-3.webp",
    name: "Cyclocybe aegerita",
  },
  {
    id: "2c-cyclocybe-aegerita-4",
    group: "2c",
    image: "https://i.ibb.co/HfxWKnQL/2c-Cyclocybe-aegerita-4.webp",
    name: "Cyclocybe aegerita",
  },
  {
    id: "2c-hemileccinum-impolitum-1",
    group: "2c",
    image: "https://i.ibb.co/jv1cxm3J/2c-Hemileccinum-impolitum-1.webp",
    name: "Hemileccinum impolitum",
  },
  {
    id: "2c-hemileccinum-impolitum-2",
    group: "2c",
    image: "https://i.ibb.co/Z6wk9GnW/2c-Hemileccinum-impolitum-2.webp",
    name: "Hemileccinum impolitum",
  },
  {
    id: "2c-hemileccinum-impolitum-3",
    group: "2c",
    image: "https://i.ibb.co/HDypLNB5/2c-Hemileccinum-impolitum-3.webp",
    name: "Hemileccinum impolitum",
  },
  {
    id: "2c-hydnum-albidum-1",
    group: "2c",
    image: "https://i.ibb.co/bgXBYWVx/2c-Hydnum-albidum-1.webp",
    name: "Hydnum albidum",
  },
  {
    id: "2c-hydnum-albidum-2",
    group: "2c",
    image: "https://i.ibb.co/N8N0s2X/2c-Hydnum-albidum-2.webp",
    name: "Hydnum albidum",
  },
  {
    id: "2c-hydnum-repandum-2",
    group: "2c",
    image: "https://i.ibb.co/5hjyT4Hv/2c-Hydnum-repandum-2.webp",
    name: "Hydnum repandum",
  },
  {
    id: "2c-hydnum-rufescens-1",
    group: "2c",
    image: "https://i.ibb.co/V0dRLqBR/2c-Hydnum-rufescens-1.webp",
    name: "Hydnum rufescens",
  },
  {
    id: "2c-hygrophorus-penarioides-1",
    group: "2c",
    image: "https://i.ibb.co/qY3zc8VL/2c-Hygrophorus-penarioides-1.webp",
    name: "Hygrophorus penarioides",
  },
  {
    id: "2c-hygrophorus-penarioides-2",
    group: "2c",
    image: "https://i.ibb.co/fz5Tzgdj/2c-Hygrophorus-penarioides-2.webp",
    name: "Hygrophorus penarioides",
  },
  {
    id: "2c-hygrophorus-russula-1",
    group: "2c",
    image: "https://i.ibb.co/hRgFZMNc/2c-Hygrophorus-russula-1.webp",
    name: "Hygrophorus russula",
  },
  {
    id: "2c-hygrophorus-russula-2",
    group: "2c",
    image: "https://i.ibb.co/hxcNP0rS/2c-Hygrophorus-russula-2.webp",
    name: "Hygrophorus russula",
  },
  {
    id: "2c-infundibulicybe-geotropa-1",
    group: "2c",
    image: "https://i.ibb.co/FLx9Z8jj/2c-Infundibulicybe-geotropa-1.webp",
    name: "Infundibulicybe geotropa",
  },
  {
    id: "2c-lactarius-deliciosus-1",
    group: "2c",
    image: "https://i.ibb.co/pB7Z4Rp0/2c-Lactarius-deliciosus-1.webp",
    name: "Lactarius deliciosus",
  },
  {
    id: "2c-lactarius-deliciosus-2",
    group: "2c",
    image: "https://i.ibb.co/ghmqT4d/2c-Lactarius-deliciosus-2.webp",
    name: "Lactarius deliciosus",
  },
  {
    id: "2c-lactarius-sanguifluus-1",
    group: "2c",
    image: "https://i.ibb.co/ZRNmXkK1/2c-Lactarius-sanguifluus-1.webp",
    name: "Lactarius sanguifluus",
  },
  {
    id: "2c-lactarius-sanguifluus-2",
    group: "2c",
    image: "https://i.ibb.co/39893d3F/2c-Lactarius-sanguifluus-2.webp",
    name: "Lactarius sanguifluus",
  },
  {
    id: "2c-lactarius-sanguifluus-3",
    group: "2c",
    image: "https://i.ibb.co/RT7W0BxL/2c-Lactarius-sanguifluus-3.webp",
    name: "Lactarius sanguifluus",
  },
  {
    id: "2c-lactarius-sanguifluus-4",
    group: "2c",
    image: "https://i.ibb.co/9k7pDPPT/2c-Lactarius-sanguifluus-4.webp",
    name: "Lactarius sanguifluus",
  },
  {
    id: "2c-lactarius-sanguifluus-5",
    group: "2c",
    image: "https://i.ibb.co/wZXnHGc2/2c-Lactarius-sanguifluus-5.webp",
    name: "Lactarius sanguifluus",
  },
  {
    id: "2c-leccinellum-crocipodium-1",
    group: "2c",
    image: "https://i.ibb.co/zHrQrm13/2c-Leccinellum-crocipodium-1.webp",
    name: "Leccinellum crocipodium",
  },
  {
    id: "2c-leccinellum-crocipodium-2",
    group: "2c",
    image: "https://i.ibb.co/5WLB4R1N/2c-Leccinellum-crocipodium-2.webp",
    name: "Leccinellum crocipodium",
  },
  {
    id: "2c-leccinellum-crocipodium-3",
    group: "2c",
    image: "https://i.ibb.co/tM6xXRZx/2c-Leccinellum-crocipodium-3.webp",
    name: "Leccinellum crocipodium",
  },
  {
    id: "2c-leccinum-aurantiacum-1",
    group: "2c",
    image: "https://i.ibb.co/yFWNX0Td/2c-Leccinum-aurantiacum-1.webp",
    name: "Leccinum aurantiacum",
  },
  {
    id: "2c-leccinum-duriusculum-1",
    group: "2c",
    image: "https://i.ibb.co/vvHGx6VR/2c-Leccinum-duriusculum-1.webp",
    name: "Leccinum duriusculum",
  },
  {
    id: "2c-leccinum-quercinum-1",
    group: "2c",
    image: "https://i.ibb.co/BVs7LS5g/2c-Leccinum-quercinum-1.webp",
    name: "Leccinum quercinum",
  },
  {
    id: "2c-leccinum-quercinum-2",
    group: "2c",
    image: "https://i.ibb.co/PSRRJTT/2c-Leccinum-quercinum-2.webp",
    name: "Leccinum quercinum",
  },
  {
    id: "2c-macrolepiota-mastoidea-1",
    group: "2c",
    image: "https://i.ibb.co/9k0smgB3/2c-Macrolepiota-mastoidea-1.webp",
    name: "Macrolepiota mastoidea",
  },
  {
    id: "2c-macrolepiota-mastoidea-2",
    group: "2c",
    image: "https://i.ibb.co/vFGsfNb/2c-Macrolepiota-mastoidea-2.webp",
    name: "Macrolepiota mastoidea",
  },
  {
    id: "2c-macrolepiota-procera-1",
    group: "2c",
    image: "https://i.ibb.co/LhpFcJxN/2c-Macrolepiota-procera-1.webp",
    name: "Macrolepiota procera",
  },
  {
    id: "2c-macrolepiota-procera-2",
    group: "2c",
    image: "https://i.ibb.co/f34J0fd/2c-Macrolepiota-procera-2.webp",
    name: "Macrolepiota procera",
  },
  {
    id: "2c-macrolepiota-procera-3",
    group: "2c",
    image: "https://i.ibb.co/5hpNvfG5/2c-Macrolepiota-procera-3.webp",
    name: "Macrolepiota procera",
  },
  {
    id: "2c-macrolepiota-procera-4",
    group: "2c",
    image: "https://i.ibb.co/d4Gsb1v2/2c-Macrolepiota-procera-4.webp",
    name: "Macrolepiota procera",
  },
  {
    id: "2c-marasmius-oreades-1",
    group: "2c",
    image: "https://i.ibb.co/X6J27st/2c-Marasmius-oreades-1.webp",
    name: "Marasmius oreades",
  },
  {
    id: "2c-marasmius-oreades-2",
    group: "2c",
    image: "https://i.ibb.co/6RqnqWcD/2c-Marasmius-oreades-2.webp",
    name: "Marasmius oreades",
  },
  {
    id: "2c-morchella-conica-1",
    group: "2c",
    image: "https://i.ibb.co/0yXDcyh6/2c-Morchella-conica-1.webp",
    name: "Morchella conica",
  },
  {
    id: "2c-morchella-conica-2",
    group: "2c",
    image: "https://i.ibb.co/gFjf3Xh7/2c-Morchella-conica-2.webp",
    name: "Morchella conica",
  },
  {
    id: "2c-morchella-conica-3",
    group: "2c",
    image: "https://i.ibb.co/RpVvJrCf/2c-Morchella-conica-3.webp",
    name: "Morchella conica",
  },
  {
    id: "2c-morchella-conica-4",
    group: "2c",
    image: "https://i.ibb.co/FLS84nP6/2c-Morchella-conica-4.webp",
    name: "Morchella conica",
  },
  {
    id: "2c-morchella-esculenta-1",
    group: "2c",
    image: "https://i.ibb.co/7N8bVYRj/2c-Morchella-esculenta-1.webp",
    name: "Morchella esculenta",
  },
  {
    id: "2c-pleurotus-ostreatus-1",
    group: "2c",
    image: "https://i.ibb.co/rR6TJcxj/2c-Pleurotus-ostreatus-1.webp",
    name: "Pleurotus ostreatus",
  },
  {
    id: "2c-russula-aurea-1",
    group: "2c",
    image: "https://i.ibb.co/0jmdt9bk/2c-Russula-aurea-1.webp",
    name: "Russula aurea",
  },
  {
    id: "2c-russula-aurea-2",
    group: "2c",
    image: "https://i.ibb.co/FLxM6dfT/2c-Russula-aurea-2.webp",
    name: "Russula aurea",
  },
  {
    id: "2c-russula-cyanoxantha-1",
    group: "2c",
    image: "https://i.ibb.co/7J9j9BMJ/2c-Russula-cyanoxantha-1.webp",
    name: "Russula cyanoxantha",
  },
  {
    id: "2c-russula-cyanoxantha-2",
    group: "2c",
    image: "https://i.ibb.co/YB8X07Tb/2c-Russula-cyanoxantha-2.webp",
    name: "Russula cyanoxantha",
  },
  {
    id: "2c-russula-delica-1",
    group: "2c",
    image: "https://i.ibb.co/pBXkDP7F/2c-Russula-delica-1.webp",
    name: "Russula delica",
  },
  {
    id: "2c-russula-delica-2",
    group: "2c",
    image: "https://i.ibb.co/MDMk3Ryy/2c-Russula-delica-2.webp",
    name: "Russula delica",
  },
  {
    id: "2c-russula-heterophylla-1",
    group: "2c",
    image: "https://i.ibb.co/7d8wWWPr/2c-Russula-heterophylla-1.webp",
    name: "Russula heterophylla",
  },
  {
    id: "2c-russula-heterophylla-2",
    group: "2c",
    image: "https://i.ibb.co/BVMHk0gq/2c-Russula-heterophylla-2.webp",
    name: "Russula heterophylla",
  },
  {
    id: "2c-russula-vesca-1",
    group: "2c",
    image: "https://i.ibb.co/YFzxhycM/2c-Russula-vesca-1.webp",
    name: "Russula vesca",
  },
  {
    id: "2c-russula-vesca-2",
    group: "2c",
    image: "https://i.ibb.co/DDzQ42q2/2c-Russula-vesca-2.webp",
    name: "Russula vesca",
  },
  {
    id: "2c-russula-vesca-3",
    group: "2c",
    image: "https://i.ibb.co/9mYxrb0V/2c-Russula-vesca-3.webp",
    name: "Russula vesca",
  },
  {
    id: "2c-russula-vesca-4",
    group: "2c",
    image: "https://i.ibb.co/FbSPVWch/2c-russula-vesca-4.webp",
    name: "Russula vesca",
  },
  {
    id: "2c-russula-virescens-1",
    group: "2c",
    image: "https://i.ibb.co/0R381NYw/2c-Russula-virescens-1.webp",
    name: "Russula virescens",
  },
  {
    id: "2c-russula-virescens-2",
    group: "2c",
    image: "https://i.ibb.co/v6GJjZq4/2c-Russula-virescens-2.webp",
    name: "Russula virescens",
  },
  {
    id: "2c-suillus-granulatus-1",
    group: "2c",
    image: "https://i.ibb.co/zTPPYZZY/2c-Suillus-granulatus-1.webp",
    name: "Suillus granulatus",
  },
  {
    id: "2c-suillus-granulatus-2",
    group: "2c",
    image: "https://i.ibb.co/n8jtwdPP/2c-Suillus-granulatus-2.webp",
    name: "Suillus granulatus",
  },
  {
    id: "2c-suillus-granulatus-3",
    group: "2c",
    image: "https://i.ibb.co/0y0vXc9Z/2c-Suillus-granulatus-3.webp",
    name: "Suillus granulatus",
  },
  {
    id: "2c-suillus-granulatus-4",
    group: "2c",
    image: "https://i.ibb.co/3Yf0MVkM/2c-Suillus-granulatus-4.webp",
    name: "Suillus granulatus",
  },
  {
    id: "2c-suillus-granulatus-5",
    group: "2c",
    image: "https://i.ibb.co/RFTYNx2/2c-Suillus-granulatus-5.webp",
    name: "Suillus granulatus",
  },
  {
    id: "2c-suillus-luteus-1",
    group: "2c",
    image: "https://i.ibb.co/tpqYDjLs/2c-Suillus-luteus-1.webp",
    name: "Suillus luteus",
  },
  {
    id: "2c-suillus-luteus-2",
    group: "2c",
    image: "https://i.ibb.co/fYBbJ7jH/2c-Suillus-luteus-2.webp",
    name: "Suillus luteus",
  },
  {
    id: "2c-tricholoma-acerbum-1",
    group: "2c",
    image: "https://i.ibb.co/hRyMgzx7/2c-Tricholoma-acerbum-1.webp",
    name: "Tricholoma acerbum",
  },
  {
    id: "2c-tricholoma-acerbum-2",
    group: "2c",
    image: "https://i.ibb.co/xK0D6Ljp/2c-Tricholoma-acerbum-2.webp",
    name: "Tricholoma acerbum",
  },
  {
    id: "2c-tricholoma-acerbum-3",
    group: "2c",
    image: "https://i.ibb.co/2YgxDhmK/2c-Tricholoma-acerbum-3.webp",
    name: "Tricholoma acerbum",
  },
  {
    id: "2c-tricholoma-terreum-1",
    group: "2c",
    image: "https://i.ibb.co/nMzHZG8S/2c-Tricholoma-terreum-1.webp",
    name: "Tricholoma terreum",
  },
  {
    id: "2c-tricholoma-terreum-2",
    group: "2c",
    image: "https://i.ibb.co/dwtmqtd0/2c-Tricholoma-terreum-2.webp",
    name: "Tricholoma terreum",
  },
  {
    id: "2c-tricholoma-terreum-3",
    group: "2c",
    image: "https://i.ibb.co/bjCHWqz7/2c-Tricholoma-terreum-3.webp",
    name: "Tricholoma terreum",
  },
  {
    id: "2c-xerocomus-dryophilus-1",
    group: "2c",
    image: "https://i.ibb.co/39YmXr64/2c-Xerocomus-dryophilus-1.webp",
    name: "Xerocomus dryophilus",
  },
  {
    id: "2c-xerocomus-dryophylus-2",
    group: "2c",
    image: "https://i.ibb.co/HTwYwBts/2c-Xerocomus-dryophylus-2.webp",
    name: "Xerocomus dryophilus",
  },
  {
    id: "2c-xerocomus-subtomentosus-1",
    group: "2c",
    image: "https://i.ibb.co/fzq3tnk3/2c-Xerocomus-subtomentosus-1.webp",
    name: "Xerocomus subtomentosus",
  },
];
