import type { QuizQuestion } from "@/lib/types";

export const mockQuizQuestions: QuizQuestion[] = [
  {
    id: "MOCK-A1",
    group: "A",
    question: "I funghi sono organismi che:",
    options: [
      "contengono sempre clorofilla",
      "non contengono clorofilla",
      "crescono solo sottoterra",
    ],
    correctIndex: 1,
  },
  {
    id: "MOCK-A2",
    group: "A",
    question: "Il micelio è:",
    options: [
      "la parte vegetativa del fungo",
      "il cappello del fungo",
      "la parte tossica del fungo",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-A3",
    group: "A",
    question: "Le spore nei funghi servono:",
    options: ["alla riproduzione", "alla digestione", "alla cottura"],
    correctIndex: 0,
  },
  {
    id: "MOCK-A4",
    group: "A",
    question: "I funghi epigei crescono:",
    options: ["sopra il suolo", "solo sui tronchi", "solo in acqua"],
    correctIndex: 0,
  },
  {
    id: "MOCK-A5",
    group: "A",
    question: "La volva è:",
    options: [
      "una parte presente solo in alcune specie",
      "un tipo di radice",
      "sempre assente nei funghi lamellati",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-A6",
    group: "A",
    question: "Il colore del fungo:",
    options: [
      "può aiutare il riconoscimento",
      "non ha mai importanza",
      "indica sempre tossicità",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-B1",
    group: "B",
    question: "Un fungo tossico:",
    options: [
      "può avere anche sapore gradevole",
      "si riconosce sempre dall'odore",
      "diventa innocuo con la cottura",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-B2",
    group: "B",
    question: "L'Amanita phalloides è:",
    options: ["commestibile", "mortale", "innocua da cotta"],
    correctIndex: 1,
  },
  {
    id: "MOCK-B3",
    group: "B",
    question: "I funghi tossici cotti insieme a quelli commestibili:",
    options: [
      "possono causare avvelenamento",
      "diventano innocui",
      "si riconoscono dal colore della pentola",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-B4",
    group: "B",
    question: "Se insorgono disturbi dopo aver mangiato funghi occorre:",
    options: [
      "andare al pronto soccorso",
      "aspettare il giorno dopo",
      "bere latte caldo",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-B5",
    group: "B",
    question: "I funghi mortali possono essere confusi con specie commestibili:",
    options: ["sì", "no", "solo da crudi"],
    correctIndex: 0,
  },
  {
    id: "MOCK-B6",
    group: "B",
    question: "Un fungo commestibile ma alterato:",
    options: [
      "può diventare pericoloso",
      "resta sempre sicuro",
      "migliora con la cottura",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-C1",
    group: "C",
    question: "I funghi vanno consumati:",
    options: [
      "con moderazione",
      "in grandi quantità",
      "solo a colazione",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-C2",
    group: "C",
    question: "In caso di dubbio sulla commestibilità dei funghi bisogna rivolgersi:",
    options: [
      "ai micologi dell'AST",
      "a un vicino di casa",
      "a un social network",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-C3",
    group: "C",
    question: "Le sindromi a lunga incubazione sono:",
    options: [
      "potenzialmente mortali",
      "sempre lievi",
      "sempre innocue",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-C4",
    group: "C",
    question: "L'Ispettorato Micologico rilascia:",
    options: [
      "certificazione sanitaria di commestibilità",
      "permesso di raccolta notturna",
      "autorizzazione alla vendita online",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-C5",
    group: "C",
    question: "I funghi in peso fresco contengono:",
    options: ["80-90% di acqua", "10% di acqua", "nessuna acqua"],
    correctIndex: 0,
  },
  {
    id: "MOCK-C6",
    group: "C",
    question: "In caso di sospetta intossicazione da funghi è utile:",
    options: [
      "portare gli avanzi al pronto soccorso",
      "buttare tutto immediatamente",
      "bere solo acqua",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-D1",
    group: "D",
    question: "La raccolta dei funghi è consentita:",
    options: [
      "dall'alba al tramonto",
      "solo di notte",
      "a qualunque ora",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-D2",
    group: "D",
    question: "La quantità massima giornaliera di raccolta è:",
    options: ["3 kg", "5 kg", "illimitata"],
    correctIndex: 0,
  },
  {
    id: "MOCK-D3",
    group: "D",
    question: "I funghi raccolti vanno trasportati:",
    options: [
      "in contenitori rigidi e aerati",
      "in sacchetti di plastica chiusi",
      "in qualunque contenitore",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-D4",
    group: "D",
    question: "L'uso di rastrelli per la raccolta è:",
    options: ["vietato", "sempre consentito", "obbligatorio"],
    correctIndex: 0,
  },
  {
    id: "MOCK-D5",
    group: "D",
    question: "Per raccogliere funghi serve:",
    options: [
      "abilitazione e titolo per la raccolta, salvo casi previsti",
      "solo un documento d'identità",
      "solo una tessera sanitaria",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-D6",
    group: "D",
    question: "La pulizia sommaria dei funghi raccolti deve avvenire:",
    options: ["in loco", "a casa", "mai"],
    correctIndex: 0,
  },
  {
    id: "MOCK-E1",
    group: "E",
    question: "I funghi sono utili al bosco:",
    options: [
      "sì, la loro presenza indica un ecosistema in salute",
      "no, vanno sempre eliminati",
      "solo quelli commestibili",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-E2",
    group: "E",
    question: "Un ecosistema boschivo è:",
    options: [
      "un insieme in equilibrio di elementi viventi e non viventi",
      "solo un insieme di alberi alti",
      "solo un'area privata",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-E3",
    group: "E",
    question: "Nella raccolta dei funghi l'uso di rastrelli è vietato:",
    options: [
      "per non danneggiare il terreno",
      "solo in città",
      "solo d'inverno",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-E4",
    group: "E",
    question: "Nelle aree naturali protette la raccolta dei funghi:",
    options: [
      "è disciplinata dagli organismi di gestione",
      "è sempre libera",
      "non è mai regolata",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-E5",
    group: "E",
    question: "I funghi appartengono:",
    options: [
      "a un regno a sé stante",
      "al regno vegetale",
      "al regno animale",
    ],
    correctIndex: 0,
  },
  {
    id: "MOCK-E6",
    group: "E",
    question: "Che cos'è un prato perenne:",
    options: [
      "un ecosistema con vegetazione erbacea",
      "un prato sempre irrigato",
      "un pascolo esclusivamente bovino",
    ],
    correctIndex: 0,
  },
];
